chatbot:
  model: gpt-4o-mini
  temperature: 0
  embedding_model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
  content_field: "combined_text"
  knn_field: "vector_combined_text"
  k: 3
  trim_messages: 4

api:
  graph_name: qna_chatbot